name: "imdb_snowflake"
version: "1.0"
profile: "imdb_snowflake"
config-version: 2

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  imdb_snowflake:
    #+schema: ANALYTICS          # <-- ensure all models land in IMDB.ANALYTICS
    +materialized: table        # <-- default materialization
    +persist_docs:
      relation: true
      columns: true
      
on-run-start:
  - "USE ROLE IMDB_ROLE"
  - "USE WAREHOUSE IMDB_WH"
  #- "USE DATABASE IMDB"
  - "USE SCHEMA ANALYTICS"
    